/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "logger_constants.h"



const loggerConstants g_logger_constants;

loggerConstants::loggerConstants() {
}



