// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Logger.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class LoggerHandler : virtual public LoggerIf {
 public:
  LoggerHandler() {
    // Your initialization goes here
  }

  int32_t AddLog(const std::string& level, const std::string& module_name, const std::string& message) {
    // Your implementation goes here
    printf("AddLog\n");
  }

  int32_t orisolLog(const std::string& level, const std::string& module_name, const std::string& message) {
    // Your implementation goes here
    printf("orisolLog\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<LoggerHandler> handler(new LoggerHandler());
  ::std::shared_ptr<TProcessor> processor(new LoggerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

