// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logger.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_logger_2eproto__INCLUDED
#define GRPC_logger_2eproto__INCLUDED

#include "logger.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace logger {

// The greeting service definition.
class Logger final {
 public:
  static constexpr char const* service_full_name() {
    return "logger.Logger";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status AddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::logger::LogReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>> AsyncAddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>>(AsyncAddLogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>> PrepareAsyncAddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>>(PrepareAsyncAddLogRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>* AsyncAddLogRaw(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logger::LogReply>* PrepareAsyncAddLogRaw(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status AddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::logger::LogReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logger::LogReply>> AsyncAddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logger::LogReply>>(AsyncAddLogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logger::LogReply>> PrepareAsyncAddLog(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logger::LogReply>>(PrepareAsyncAddLogRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, std::function<void(::grpc::Status)>) override;
      void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void AddLog(::grpc::ClientContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void AddLog(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::logger::LogReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::logger::LogReply>* AsyncAddLogRaw(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logger::LogReply>* PrepareAsyncAddLogRaw(::grpc::ClientContext* context, const ::logger::LogRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddLog_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status AddLog(::grpc::ServerContext* context, const ::logger::LogRequest* request, ::logger::LogReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddLog() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddLog(::grpc::ServerContext* context, ::logger::LogRequest* request, ::grpc::ServerAsyncResponseWriter< ::logger::LogReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddLog<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_AddLog() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::logger::LogRequest, ::logger::LogReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::logger::LogRequest* request, ::logger::LogReply* response) { return this->AddLog(context, request, response); }));}
    void SetMessageAllocatorFor_AddLog(
        ::grpc::experimental::MessageAllocator< ::logger::LogRequest, ::logger::LogReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::logger::LogRequest, ::logger::LogReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AddLog(
      ::grpc::CallbackServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AddLog(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_AddLog<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_AddLog<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddLog() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddLog() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddLog(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_AddLog() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddLog(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AddLog(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AddLog(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddLog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddLog() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::logger::LogRequest, ::logger::LogReply>(std::bind(&WithStreamedUnaryMethod_AddLog<BaseClass>::StreamedAddLog, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AddLog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddLog(::grpc::ServerContext* /*context*/, const ::logger::LogRequest* /*request*/, ::logger::LogReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddLog(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::logger::LogRequest,::logger::LogReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddLog<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddLog<Service > StreamedService;
};

}  // namespace logger


#endif  // GRPC_logger_2eproto__INCLUDED
